### ISSUE TITLE
"No connection..." flickers on and off.

### ISSUE THREAD

**Issue by tangles-0** [tgreer/inav-telemscript#3]
As per title - error flashes up even though telemetry stream is working fine. See video of the issue: https://www.youtube.com/watch?v=KAUQSNeCJPs

- Taranis X9D+ running OpenTX 2.2.4
- TBS Crossfire
- F405wing running iNav 2.2.1

**Comment by tgreer** [comment]
Hi @Energiz3r, this is based on RSSI. You may find you're too close. Try being slightly further away. 

Also look at the raw telemetry values under the model. 1RSS and 2RSS are the figures used. There is some maths which says: take the maximum of either of these 2 values. As long as RSSI is >25 it'll show the full screen, otherwise it'll show No Connection.

**Comment by tangles-0** [comment]
Ah - for me those figures are sitting around 25 and the units defaults to dBm which I believe may be the automatic transmit power level? Or perhaps it is RSSI but scaled wrongly by my Taranis.

According to this link https://oscarliang.com/lq-rssi-tbs-crossfire/ the Crossfire supplies the LQ (link quality) telemetry figures named as RQly and TQly, which are a measure of packet transmission success which is probably more of a useful measure than RSSI, so I will edit the script to suit - lines 606 and 607. I'll also alter line 658 to kick in the rather absolute 'No connection' message below 1 LQ instead of 25 - the Crossfire TX will report a reading above 0 if there is any successful connection at all, so I'll still want the telemetry to display.

In saying all that, a warning might be a more useful measure. But enough negatives, this script is really awesome, well done :) Lovely neat code, too. Thanks for sharing

**Comment by tgreer** [comment]
I'd need to dig my Taranis out to check. I'll try and look at it this weekend. I don't know if those figures were available when I was working on this initially!

**Comment by tangles-0** [comment]
Thanks for taking a look so quickly. Happy for you to close the issue if you like, seems like a simple enough fix
